<?php

if (!defined('BASEPATH'))
	exit('No direct script access allowed');

class Buat_Laporan_kehilangan extends CI_Controller
{
	function __construct()
	{
		parent::__construct();
		$this->load->model('Buat_laporan_kehilangan_model');
		$this->load->library('form_validation');
	}

	public function index()
	{
		if (empty($this->session->userdata('email'))) {
			redirect(base_url('index.php/auth'));
		}else{
		$kotomatis = $this->Buat_laporan_kehilangan_model->buat_kode(); // variable $kodeunik merujuk ke file model_user.php pada function buat_kode. paham kan ya? harus paham dong
		// $this->load->view('template/backend', $data);
		$user = $this->Buat_laporan_kehilangan_model->get();

		$data = array(
			'iduser' => $user,
			'kodeunik' => $kotomatis
		);

		$this->load->view('buat_laporan_kehilangan', $data);
	}
}

public function upload(){
		$config['upload_path']          = './images/';
		$config['allowed_types']        = 'png|jpg|gif';
		$config['max_size']             = 2048;
		$config['max_width']            = 40000;
		$config['max_height']           = 40000;

		$this->load->library('upload', $config);

		if ( ! $this->upload->do_upload('foto_barang'))
		{
				$error = array('error' => $this->upload->display_errors());
				$this->load->view('welcome_message', $error);
		}
		else{
			$upload_data = $this->upload->data();
			$name = $upload_data['file_name'];

			$insert = $this->Buat_laporan_kehilangan_model->insertGambar($name);
			$insertlaporan = $this->Buat_laporan_kehilangan_model->insertlaporan();

			if (($insert) && ($insertlaporan)) {
				$this->session->set_flashdata("message", "<div class='alert alert-success' role='alert'>Laporan Anda Sudah DI Masukuan</div>");
				redirect(base_url('index.php/Buat_laporan_kehilangan'));
			}else{
				$this->session->set_flashdata("message", "<div class='alert alert-warning' role='alert'>Laporan Anda gagal Di masukan</div>");
				redirect(base_url('index.php/Buat_laporan_kehilangan'));
			}
		}
	}


	// public function tambahdata(){
	// 	$id_user = $this->input->post('id_user');
	// 	$id_barang = $this->input->post('id_barang');
	// 	$nama_barang = ($this->input->post('nama_barang'));
	// 	$des = $this->input->post('des_barang');
	// 	$jenis = $this->input->post('jenis_barang');
	// 	$foto = $this->input->post('foto_barang');
	// 	$tgl = $this->input->post('tgl');
	// 	$lokasi = $this->input->post('lokasi');

	// 	$databarang = ['id_barang'=>$id_barang, 'nama_barang'=>$nama_barang, 'deskripsi_barang'=>$des, 'jenis_barang'=>$jenis, 'foto'=>$foto, 'p'=>"1"];

	// 	$datalaporankehilangan = ['id_user'=>$id_user, 'id_barang'=>$id_barang,  'tgl_kehilangan'=>$tgl, 'lokasi_kehilangan'=>$lokasi, 'p'=>"1"];

	// 	$sql1 = $this->Buat_laporan_model->InputData('barang',$databarang);
	// 	$sql2 = $this->Buat_laporan_model->InputData('l_kehilangan',$datalaporankehilangan);

	// 	if (($sql1) && ($sql2)) {
	// 		$this->session->set_flashdata("pesan", "<div class='alert alert-success' role='alert'>Data sudah dimasukan</div>");
	// 		redirect("Buat_laporan");
	// 	}else{
	// 		$this->session->set_flashdata("pesan", "<div class='alert alert-warning' role='alert'>Data gagal dimasukan</div>");
	// 		redirect("Belajar");
	// 	}
	// }


}

/* End of file Barang.php */
/* Location: ./application/controllers/Barang.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-06-20 13:20:23 */
/* http://harviacode.com */