<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Login_model extends CI_Model
{

    public $table = 'login';
    public $ids = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    public function GetDataJoin($query){
        return $this->db->query($query)->result();
    }
    function fet_all_by_access($query){
        return $this->db->query($query)->result();
    }


    function get_all()
    {
        $this->db->order_by($this->ids, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->ids, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
        $this->db->like('nama_user', $q);
        $this->db->like('email', $q);
        $this->db->or_like('password', $q);
        $this->db->or_like('hak_akses', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->ids, $this->order);
        $this->db->like('id', $q);
        $this->db->like('nama_user', $q);
        $this->db->like('email', $q);
        $this->db->or_like('password', $q);
        $this->db->or_like('hak_akses', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->ids, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->ids, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Login_model.php */
/* Location: ./application/models/Login_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-06-20 13:20:23 */
/* http://harviacode.com */